name: Update Cache

on:
  schedule:
    - cron: '*/40 * * * *'

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Curl updateCache endpoint
        env:
          UPDATE_CACHE_API_KEY: ${{ secrets.UPDATE_CACHE_API_KEY }}
        run: curl -X GET https://<your-vercel-deployment-url>/api/updateCache -H "x-api-key: $UPDATE_CACHE_API_KEY"
